#!/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at COPYING
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at COPYING.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2010,2011 Joyent Inc.
# Portions Copyright 2012 Every Ware Ltd.

set -o xtrace

. /lib/svc/share/smf_include.sh
. /lib/sdc/config.sh

# first of all, if we aren't the global zone this doesn't make any sense to run

smf_is_globalzone || exit $SMF_EXIT_OK

if [ -f "${CONFIG_config_inc_dir}/ipnat.conf" ] ; then
    svccfg -s svc:/network/ipfilter:default setprop \
	config/ipnat_config_file=${CONFIG_config_inc_dir}/ipnat.conf
    svccfg -s svc:/network/ipfilter:default refresh
fi

exit $SMF_EXIT_OK

